/*
stylelint rules: https://github.com/stylelint/stylelint/blob/main/docs/user-guide/rules.md
standard config: https://github.com/stylelint/stylelint-config-standard/blob/main/index.js
recommended config: https://github.com/stylelint/stylelint-config-recommended/blob/main/index.js

scss rules: https://github.com/stylelint-scss/stylelint-scss
standard scss config: https://github.com/stylelint-scss/stylelint-config-standard-scss/blob/HEAD/index.js
recommended scss config: https://github.com/stylelint-scss/stylelint-config-recommended-scss/blob/HEAD/index.js
*/

module.exports = {
	extends: 'stylelint-config-standard-scss',
	plugins: ['@namics/stylelint-bem'],
	rules: {
		'plugin/stylelint-bem-namics': true,
		'alpha-value-notation': ['number', { severity: 'warning' }],
		'at-rule-no-unknown': null,
		'at-rule-no-vendor-prefix': true,
		'at-rule-empty-line-before': null,
		'block-no-empty': null,
		'color-function-notation': ['modern', { severity: 'warning' }],
		'color-named': 'never',
		'color-no-invalid-hex': [true, { severity: 'warning' }],
		'comment-word-disallowed-list': ['todo', { severity: 'warning' }],
		'custom-media-pattern': null,
		'custom-property-pattern': null,
		'declaration-block-no-duplicate-properties': [
			true,
			{ ignore: ['consecutive-duplicates-with-different-values'], severity: 'warning' },
		],
		'declaration-block-no-shorthand-property-overrides': true,
		'declaration-no-important': true,
		'declaration-empty-line-before': null,
		'declaration-block-no-redundant-longhand-properties': true,
		'function-linear-gradient-no-nonstandard-direction': [true, { severity: 'warning' }],
		'function-name-case': 'lower',
		'keyframes-name-pattern': null,
		'length-zero-no-unit': true,
		'max-nesting-depth': [2, { severity: 'warning' }],
		'no-descending-specificity': null,
		'no-duplicate-selectors': [true, { severity: 'warning' }],
		'no-empty-source': null,
		'no-unknown-animations': [true, { severity: 'warning' }],
		'number-max-precision': 4,
		'property-no-unknown': [true, { ignoreProperties: 'font-icon' }],
		'property-no-vendor-prefix': [true, { severity: 'warning' }],
		'rule-empty-line-before': null,
		'scss/at-else-closing-brace-newline-after': null,
		'scss/at-else-closing-brace-space-after': null,
		'scss/at-function-pattern': null,
		'scss/at-if-closing-brace-newline-after': null,
		'scss/at-if-closing-brace-space-after': null,
		'scss/at-if-no-null': null,
		'scss/at-import-partial-extension': ['never', { severity: 'warning' }],
		'scss/at-import-no-partial-leading-underscore': null,
		'scss/at-mixin-argumentless-call-parentheses': 'always',
		'scss/at-mixin-pattern': null,
		'scss/at-rule-conditional-no-parentheses': null,
		'scss/at-rule-no-unknown': true,
		'scss/comment-no-empty': null,
		'scss/declaration-nested-properties': 'never',
		'scss/declaration-nested-properties-no-divided-groups': null,
		'scss/dollar-variable-pattern': null,
		'scss/dollar-variable-empty-line-before': null,
		'scss/double-slash-comment-empty-line-before': null,
		'scss/double-slash-comment-whitespace-inside': null,
		'scss/no-global-function-names': null,
		'scss/operator-no-newline-after': true,
		'scss/operator-no-newline-before': true,
		'scss/selector-no-redundant-nesting-selector': true,
		'scss/selector-no-union-class-name': true,
		'selector-class-pattern': null,
		'selector-id-pattern': null,
		'selector-max-id': 0,
		'selector-not-notation': 'complex',
		'selector-pseudo-element-colon-notation': 'double',
		'selector-type-case': 'lower',
		'shorthand-property-no-redundant-values': true,
		'value-keyword-case': ['lower', { camelCaseSvgKeywords: true }],
		'value-no-vendor-prefix': [true, { severity: 'warning' }],
	},
};
